### ISSUE TITLE
Does not install on Windows 7 Enterprise

### ISSUE THREAD

**Issue by krrk** [DarwinJS/ChocoPackages#27]
NEW VERSIONS OF SSH EXES:
Get-Command : Cannot validate argument on parameter 'Name'. The argument is null or empty. Supply an argument that is n
ot null or empty and then try the command again.
At C:\ProgramData\chocolatey\lib-bad\openssh\tools\chocolateyinstall.ps1:535 char:51
+ (dir "$TargetFolder\*.exe").fullname | get-command <<<<  | select Source,Version | out-string
    + CategoryInfo          : InvalidData: (:) [Get-Command], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationError,Microsoft.PowerShell.Commands.GetCommandCommand

**Comment by DarwinJS** [comment]
Thanks for reporting!  Should be fixed in 0.0.10.20170331 - which is in automated moderation at this moment.

**Comment by krrk** [comment]
Okay I took some time to look into this and learn a bit of powershell (I'm a linux user). In fact there are files in there already, but it seems that in Win7 if you call `(dir <directory>\*.exe).fullname` it returns no objects if `dir` returns more than one item then when you pipe this to `get-command` it give the error I originally posted. I did some testing and you can simplify the line 535 of `chocolateyinstall.ps1` as follows:

Write-Output "$(dir "$TargetFolder\*.exe" | get-command | select Source,Version | out-string)"

This works on Windows 10 and it works on Windows 7. Calling `( ).fullname` doesn't seem to be necessary. Although the modified command does work on Windows 7 when one or multiple child objects are returned by `dir`, sadly `Get-Command` does not return any Source or Version. Note that I have Powershell 2.0 installed on windows 7. Therefore the result of the above command then is useless in PS2.0:

>     dir 'C:\Program Files\OpenSSH-Win64\*.exe' | get-command | select Source,Version
>     
>     Source                                                      Version
>     ------                                                      -------
>     
>     <continues to shows as many blank lines as was in input>
> 

as it just returns nothing. Please note that I have found that you've used `( ).fullname` on line 228 as well and I also don't see the necessity of piping to out-string.

**Comment by DarwinJS** [comment]
Nano was having problems without fullname.  What version of PowerShell is on your win 7 machine?

**Comment by krrk** [comment]
Windows 7 has version 2.0

**Comment by DarwinJS** [comment]
Yes I know the RTM shipping versions - but many have moved to 3 by now.

**Comment by krrk** [comment]
Yes, I have Windows 7 Enterprise SP1 and all Windows Updates, but
PowerShell  did not get upgraded to version 3. I know I can easily upgrade
PowerShell, but in the interest of getting your package to work for other
with a similar setup to mine, maybe you could check `(get-host).version`
and if its 2.0 or lower you could output the version string from ssh.exe:
`Write-Output (ssh.exe -V)`.

**Comment by DarwinJS** [comment]
Sure - I am not asking these questions to imply or recommend a work around for your individual case - but to understand the impact and what effort to put into a fix.

There are some substantial differences in the output object properties of v2 of get-command and subsequent versions.  If you are are preparing Windows image from RTM media - you will find that there is a lot of PowerShell code out there that will fail due to some of the object reference methods that were improved in 3.0.  When I build an image I typically get PowerShell and anything else that has to do with the automation stack up to date (e.g. install chocolatey, update .net) and then reboot before continuing automation.

I believe the bug you reported here is eliminated - code was tested on Both Win7 w/ PSH 2.0 and Nano Server.

Version 0.0.10.20170402 is in automated moderation, you can pull it before moderation is complete with:
```
cinst -y powershell -version 0.0.10.20170402
```

The version is

**Comment by krrk** [comment]
Yes, of course and now that I have verified your new version works on Win7 w/ PSH 2.0 I plan to upgrade powershell. Thanks for the fix and the package. I couldn't get key-based authentication working by following the directions on the Win32-OpenSSH github page. Glad I found your package and also chocolatey thanks to your one of your comments I read.
