### ISSUE TITLE
Chocolatey support for libressl

### ISSUE THREAD

**Issue by bagajjal** [DarwinJS/ChocoPackages#28]
Hi Darwin,

We (Win32-OpenSSH team) are moving away from OpenSSL to LibreSSL in the "april-end" release to align with the OpenSSH community. 

Looks like Chocolatey support is not there for the LibreSSL. 

When we move to LibreSSL, it would a breaking change as we depend on the LibreSSL package going forward. We plan **NOT** to take dependency on the LibreSSL for shipping our win32-openssh binaries so this will be a manual step to the end users i.e., the end users have to copy the LibreSSL DLL (Only "libcrypto-41.dll") to some directory that is included in the $env:path.

Since you are doing the chocolatey packaging for the win32-openssh, it would be great if you can create a chocolatey package for the LibreSSL (https://ftp.openbsd.org/pub/OpenBSD/LibreSSL/) and incorporate necessary steps to install the LibreSSL before installing the Win32-OpenSSH package.

Thanks,
Balu

**Comment by DarwinJS** [comment]
@bagajjal - I can surely tackle this issue.

However, right now I currently include EVERYTHING needed to install OpenSSH in the package because it is actually a universal package used to install without chocolatey and with docker.

Setting up a formal chocolatey dependency package would make these non-chocolatey scenarios non-functional.

If I am reading correctly I could redistribute the dll in the universal installer even if the OpenSSL project is choosing not to: https://github.com/libressl/libressl/blob/master/src/LICENSE

Let me know if this seems like a reasonable solution.

**Comment by bagajjal** [comment]
Sure,
We want to keep the LibreSSL and OpenSSH in two different parallel folders as they are fundamentally two different projects coming from two different communities.

<Base directory>/OpenSSH
<Base directory>/LibreSSL/libcrypto-41.dll

Thanks,

**Comment by DarwinJS** [comment]
@bagajjal - thanks!
Will openssh probe these locations and automatically find libcrypto?

If so, will the probing logic be looking specifically for libcrypto-41.dll, or just any libcrypto*.dll?

**Comment by bagajjal** [comment]
@DarwinJS - Thanks for your quick replies and taking care of it.

openssh will look for "libcrypto-41.dll" (exact name).. as long as this dll is included in a directory which is part of the $env:path variable it should work fine..

**Comment by DarwinJS** [comment]
Hmmm .... using the path would:
- require us to add "installation_directory"/LibreSSL/ to the path
- open you up to finding an unexpected version (non-isolated)

What do you think if we put it right in the "installation_directory" with the following benefits:
- DLL Search order should favor "same folder as the EXE" and not do a path search
- it will be faster to avoid the search
- you will always get the EXACT version you expect and the one that came down with the package (not corrupt)
- upgrades of the DLL will not be mysterious as it is in a known location.
- if someone wants to search the path for an existing version, they will only need to delete the one next to the EXE. (if there is enough demand we could include a switch -dontinstallssllibrary and then a path search would be natural)

If you like this proposal, I think only one small code adaptation might be helpful:
-  include logic that if both libraries are present in the installation_folder, libressl will be preferred (since it is the preferred library of the project)
- actually that logic would need to be there anyway to know which one to search the path for first - so there may not be any changes required

**Comment by bagajjal** [comment]
@DarwinJS - We would like to keep LibreSSL and OpenSSH binaries in different locations because they are from two different communities. Having them in the same folder might confuse the end users thinking OpenSSH is responsible for any bugs in the LibreSSL.
As far as I know, it wouldn't make much different for finding the DLL even if we place in a different folder.

**Comment by DarwinJS** [comment]
@bagajjal - most of my concerns are directed on relying on the path to find the library in a sub-folder of the binaries folder

While the concept of relying on the path is simple in concept - the paths of production machines are much uglier than the development machines most of us work on or on pure DevOps systems where additional software is not installed and removed over a period of years.

In many cases, the general practice is to add new path strings to the END of an already long path - which can impact load performance and the risk of finding the same named library in another location (which again, in theory should be "so what" but in practice - when installed on millions of machines - can surface unusual exceptions which end up on your doorstep as filed issues, then someone has to burn hours to figure out it's an unexpected path problem).

In addition, you will also have to rely on a second addition to the path with a common parent of the first addition - a situation that can lead to a lot of people messing up the path when doing removals, etc.

So if openssh is going to take the effort to provide an isolated copy of these libraries - then I think it would also be prudent to isolate the "loading process" for them as well.

So a way to keep them in a subfolder and avoid a path search for the DLL in most cases, it may be prudent to have openssh exes probe for the libraries at their literal sub-path locations, then if not found resort to the path.

FYI I recently blogged about the challenge of using automation to update the path here - though not directly related if you imagine a lot of the bad practices having *already happened* on many production machines, you can see how the state of the path could be pretty bad - so possibly a dependency to be avoided when loading critical code: https://cloudywindows.com/post/straight-and-narrow-code-for-safe-windows-path-updates/

**Comment by DarwinJS** [comment]
@bagajjal - I was just taking a look at the Libressl packages.  I understand now that you are proposing that libresll be in a peer folder to the entire Openssh package - apologies for the misunderstanding earlier.

For all the reasons above I would encourage an approach of having the DLL in a subfolder.

Additionally:
* you would have control over the version you are using via the isolation this provides (something I was *assuming* you were already seeking)
* you can take advantage of the fact that you only need the one DLL and bundle it with the OpenSSH product to keep complexity and overall file size low, this will also benefit:
  * for offline install scenarios as all files would travel within the openssh package
  * for non-chocolatey scenarios (e.g. Nano)
* In #606 @manojampalam mentions that the logs folder should be under the binaries folder because it is a goal of the project to be able to run multiple versions side-by-side - having any dependent runtimes bundled and isolated would make sure that this side-by-side capability is preserved for dependent runtimes as well.

Would the following suit the desire of the Openssh project (it will retain all the benefits I've pointed out in this thread);
1. Include Libressl as a bundled, isolated runtime in a subfolder like "..\Openssh\Libressl" - which also allows your loading of it to guarantee the tested, bundled version.
2. Include the libressl license text file in the same folder - clearly identifying the file as from another project.
3. If the license file is not considered sufficient to indicate that the file is from another project - a readme file explaining such and explaining where libressl bugs are to be reported.

**Comment by DarwinJS** [comment]
@bagajjal - while I feel it would be very beneficial to the openssh package to bundle an isolated copy of just libcrypto-41.dll and place it in a sub-folder of openssh (and not use chocolatey dependencies to accomplish the install) for the reasons discussed in this thread...

I also have had linux pros at work frustrated at the lack of openssl.exe on Windows.

So I have package libreSSL in chocolatey.

As of this writing it is still in automated review, but you can find it and install it with the commands documented from this direct link (searching on Chocolatey won't find it until it passes moderation): https://chocolatey.org/packages/libressl

**Comment by DarwinJS** [comment]
@bagajjal - has the team discussed this?

I have given it a bit more thought and having libreSSL as a separate package (rather than integrating the one needed DLL into the OpenSSH package) will make installs for Nano and other typically non-chocolatey scenarios (e.g. Docker) more complex as they will have to download and extract another package to pull the dependency DLL.

**Comment by bagajjal** [comment]
@DarwinJS - very sorry for the late reply.
We are busy fixing the stability issues. I will get back to you by tomorrow eod.

**Comment by bagajjal** [comment]
@DarwinJS - Thanks for your suggestions.
We had an internal discussion and would like to take your advice.
We will include the libressl DLL as part of our release so that non-chocolatey scenarios are also covered.
Since we are packing the libressl DLL, we may not need additional changes from chocolatey side.

Thanks again.

**Comment by DarwinJS** [comment]
@bagajjal - I'm glad the suggestions were helpful.
